version: '3.4'

services:
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    depends_on:
      - server
    ports:
      - 5173:5173